//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparky.TrakApp.ViewModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sparky.TrakApp.ViewModel.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred making the request. Please try again..
        /// </summary>
        public static string ErrorMessageApiError {
            get {
                return ResourceManager.GetString("ErrorMessageApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred making the request..
        /// </summary>
        public static string ErrorMessageGeneric {
            get {
                return ResourceManager.GetString("ErrorMessageGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentials were incorrect. Please try again..
        /// </summary>
        public static string ErrorMessageIncorrectCredentials {
            get {
                return ResourceManager.GetString("ErrorMessageIncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog.
        /// </summary>
        public static string GameUserEntryListPageBackLogTitle {
            get {
                return ResourceManager.GetString("GameUserEntryListPageBackLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string GameUserEntryListPageCompletedTitle {
            get {
                return ResourceManager.GetString("GameUserEntryListPageCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped.
        /// </summary>
        public static string GameUserEntryListPageDroppedTitle {
            get {
                return ResourceManager.GetString("GameUserEntryListPageDroppedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no games in .
        /// </summary>
        public static string GameUserEntryListPageEmpty {
            get {
                return ResourceManager.GetString("GameUserEntryListPageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load your games due to an unexpected error..
        /// </summary>
        public static string GameUserEntryListPageEmptyGenericError {
            get {
                return ResourceManager.GetString("GameUserEntryListPageEmptyGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load your games due to an error on the server..
        /// </summary>
        public static string GameUserEntryListPageEmptyServerError {
            get {
                return ResourceManager.GetString("GameUserEntryListPageEmptyServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string GameUserEntryListPagePlayingTitle {
            get {
                return ResourceManager.GetString("GameUserEntryListPagePlayingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password has been entered..
        /// </summary>
        public static string LoginErrorMessagePasswordEmpty {
            get {
                return ResourceManager.GetString("LoginErrorMessagePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username has been entered..
        /// </summary>
        public static string LoginErrorMessageUsernameEmpty {
            get {
                return ResourceManager.GetString("LoginErrorMessageUsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? .
        /// </summary>
        public static string LoginPageDontHaveAnAccount {
            get {
                return ResourceManager.GetString("LoginPageDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password?.
        /// </summary>
        public static string LoginPageForgottenPassword {
            get {
                return ResourceManager.GetString("LoginPageForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPageLogIn {
            get {
                return ResourceManager.GetString("LoginPageLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPagePassword {
            get {
                return ResourceManager.GetString("LoginPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string LoginPageSignUp {
            get {
                return ResourceManager.GetString("LoginPageSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginPageUsername {
            get {
                return ResourceManager.GetString("LoginPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string RegisterPageAlreadyHaveAccount {
            get {
                return ResourceManager.GetString("RegisterPageAlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterPageConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterPageConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string RegisterPageEmailAddress {
            get {
                return ResourceManager.GetString("RegisterPageEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string RegisterPageLogIn {
            get {
                return ResourceManager.GetString("RegisterPageLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterPagePassword {
            get {
                return ResourceManager.GetString("RegisterPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password must contain:.
        /// </summary>
        public static string RegisterPagePasswordRulesHeader {
            get {
                return ResourceManager.GetString("RegisterPagePasswordRulesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy &amp; Terms of Use.
        /// </summary>
        public static string RegisterPagePrivacyPolicyAndTermsOfUse {
            get {
                return ResourceManager.GetString("RegisterPagePrivacyPolicyAndTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string RegisterPageSignUp {
            get {
                return ResourceManager.GetString("RegisterPageSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string RegisterPageUsername {
            get {
                return ResourceManager.GetString("RegisterPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password cannot be empty or only contain whitespace..
        /// </summary>
        public static string RegistrationErrorMessageConfirmPasswordEmpty {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageConfirmPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords must match..
        /// </summary>
        public static string RegistrationErrorMessageConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot be empty or only contain whitespace..
        /// </summary>
        public static string RegistrationErrorMessageEmailAddressEmpty {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageEmailAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string RegistrationErrorMessageEmailAddressInvalid {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty or only contain whitespace..
        /// </summary>
        public static string RegistrationErrorMessagePasswordEmpty {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase character..
        /// </summary>
        public static string RegistrationErrorMessagePasswordLowercaseCharacter {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordLowercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string RegistrationErrorMessagePasswordMinimumLength {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        public static string RegistrationErrorMessagePasswordNumber {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase character..
        /// </summary>
        public static string RegistrationErrorMessagePasswordUppercaseCharacter {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordUppercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not contain any spaces..
        /// </summary>
        public static string RegistrationErrorMessagePasswordWhitespace {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty or only contain whitespace..
        /// </summary>
        public static string RegistrationErrorMessageUsernameEmpty {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageUsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username can only contain letters, numbers, under-scores and hyphens..
        /// </summary>
        public static string RegistrationErrorMessageUsernameInvalidCharacters {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageUsernameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be between 1 and 255 characters..
        /// </summary>
        public static string RegistrationErrorMessageUsernameLength {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageUsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot contain any spaces..
        /// </summary>
        public static string RegistrationErrorMessageUsernameWhitespace {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageUsernameWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games, Books, Manga, Anime.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trak.
        /// </summary>
        public static string TrakTitle {
            get {
                return ResourceManager.GetString("TrakTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code cannot be empty or only contain whitespace..
        /// </summary>
        public static string VerificationErrorMessageVerificationCodeEmpty {
            get {
                return ResourceManager.GetString("VerificationErrorMessageVerificationCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code should only contain letters and numbers..
        /// </summary>
        public static string VerificationErrorMessageVerificationCodeInvalidCharacters {
            get {
                return ResourceManager.GetString("VerificationErrorMessageVerificationCodeInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of characters. The verification code will be between 1 and 5 characters..
        /// </summary>
        public static string VerificationErrorMessageVerificationCodeLength {
            get {
                return ResourceManager.GetString("VerificationErrorMessageVerificationCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code cannot contain any spaces..
        /// </summary>
        public static string VerificationErrorMessageVerificationCodeWhitespace {
            get {
                return ResourceManager.GetString("VerificationErrorMessageVerificationCodeWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have now sent you a confirmation email with your verification code..
        /// </summary>
        public static string VerificationPageConfirmation {
            get {
                return ResourceManager.GetString("VerificationPageConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven&apos;t received an email? .
        /// </summary>
        public static string VerificationPageHaventReceivedEmail {
            get {
                return ResourceManager.GetString("VerificationPageHaventReceivedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send again.
        /// </summary>
        public static string VerificationPageSendAgain {
            get {
                return ResourceManager.GetString("VerificationPageSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you..
        /// </summary>
        public static string VerificationPageTitle {
            get {
                return ResourceManager.GetString("VerificationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string VerificationPageVerificationCode {
            get {
                return ResourceManager.GetString("VerificationPageVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerificationPageVerify {
            get {
                return ResourceManager.GetString("VerificationPageVerify", resourceCulture);
            }
        }
    }
}
