//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkyStudios.TrakLibrary.ViewModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparkyStudios.TrakLibrary.ViewModel.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The platform cannot be empty..
        /// </summary>
        public static string AddGameErrorMessagePlatformNull {
            get {
                return ResourceManager.GetString("AddGameErrorMessagePlatformNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status cannot be empty..
        /// </summary>
        public static string AddGameErrorMessageStatusNone {
            get {
                return ResourceManager.GetString("AddGameErrorMessageStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddGamePageAdd {
            get {
                return ResourceManager.GetString("AddGamePageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string AddGamePagePlatform {
            get {
                return ResourceManager.GetString("AddGamePagePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AddGamePageStatus {
            get {
                return ResourceManager.GetString("AddGamePageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog.
        /// </summary>
        public static string Backlog {
            get {
                return ResourceManager.GetString("Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string BaseMasterDetailContentPageAnime {
            get {
                return ResourceManager.GetString("BaseMasterDetailContentPageAnime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string BaseMasterDetailContentPageBooks {
            get {
                return ResourceManager.GetString("BaseMasterDetailContentPageBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string BaseMasterDetailContentPageGames {
            get {
                return ResourceManager.GetString("BaseMasterDetailContentPageGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BaseMasterDetailContentPageHome {
            get {
                return ResourceManager.GetString("BaseMasterDetailContentPageHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string BaseMasterDetailContentPageLogout {
            get {
                return ResourceManager.GetString("BaseMasterDetailContentPageLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga.
        /// </summary>
        public static string BaseMasterDetailContentPageManga {
            get {
                return ResourceManager.GetString("BaseMasterDetailContentPageManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BaseMasterDetailContentPageSettings {
            get {
                return ResourceManager.GetString("BaseMasterDetailContentPageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your email address below. Once, your email has been changed you will receive a verification email. You will have to re-verify your account..
        /// </summary>
        public static string ChangeEmailAddressPageInstructions {
            get {
                return ResourceManager.GetString("ChangeEmailAddressPageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email address.
        /// </summary>
        public static string ChangeEmailAddressPageNewEmailAddress {
            get {
                return ResourceManager.GetString("ChangeEmailAddressPageNewEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address successfully changed. You will have received a new verification email. Please login and verify your account..
        /// </summary>
        public static string ChangeEmailAddressPageSuccess {
            get {
                return ResourceManager.GetString("ChangeEmailAddressPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address.
        /// </summary>
        public static string ChangeEmailAddressPageTitle {
            get {
                return ResourceManager.GetString("ChangeEmailAddressPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ChangeEmailAddressPageUpdate {
            get {
                return ResourceManager.GetString("ChangeEmailAddressPageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangePasswordPageChange {
            get {
                return ResourceManager.GetString("ChangePasswordPageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ChangePasswordPageConfirmNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPageConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePasswordPageCurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPageCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePasswordPageNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordPageNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset token.
        /// </summary>
        public static string ChangePasswordPageResetToken {
            get {
                return ResourceManager.GetString("ChangePasswordPageResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed. Please login with your new credentials..
        /// </summary>
        public static string ChangePasswordPageSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordPageTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped.
        /// </summary>
        public static string Dropped {
            get {
                return ResourceManager.GetString("Dropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred making the request. Please try again..
        /// </summary>
        public static string ErrorMessageApiError {
            get {
                return ResourceManager.GetString("ErrorMessageApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred making the request..
        /// </summary>
        public static string ErrorMessageGeneric {
            get {
                return ResourceManager.GetString("ErrorMessageGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentials were incorrect. Please try again..
        /// </summary>
        public static string ErrorMessageIncorrectCredentials {
            get {
                return ResourceManager.GetString("ErrorMessageIncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address cannot be empty or only contain whitespace..
        /// </summary>
        public static string ForgottenPasswordErrorMessageEmailAddressEmpty {
            get {
                return ResourceManager.GetString("ForgottenPasswordErrorMessageEmailAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid..
        /// </summary>
        public static string ForgottenPasswordErrorMessageEmailAddressInvalid {
            get {
                return ResourceManager.GetString("ForgottenPasswordErrorMessageEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address cannot contain any spaces..
        /// </summary>
        public static string ForgottenPasswordErrorMessageEmailAddressWhitespace {
            get {
                return ResourceManager.GetString("ForgottenPasswordErrorMessageEmailAddressWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string ForgottenPasswordPageEmailAddress {
            get {
                return ResourceManager.GetString("ForgottenPasswordPageEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address associated with your account..
        /// </summary>
        public static string ForgottenPasswordPageInstructions {
            get {
                return ResourceManager.GetString("ForgottenPasswordPageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ForgottenPasswordPageSend {
            get {
                return ResourceManager.GetString("ForgottenPasswordPageSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred scanning the barcode. Please try again..
        /// </summary>
        public static string GameBarcodeScannerPageApiError {
            get {
                return ResourceManager.GetString("GameBarcodeScannerPageApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred scanning the barcode..
        /// </summary>
        public static string GameBarcodeScannerPageGenericError {
            get {
                return ResourceManager.GetString("GameBarcodeScannerPageGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the red line over the barcode you&apos;d like to scan..
        /// </summary>
        public static string GameBarcodeScannerPageInstructions {
            get {
                return ResourceManager.GetString("GameBarcodeScannerPageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the scanned barcode in our library. Would you like to make a request?.
        /// </summary>
        public static string GameBarcodeScannerPageMakeARequest {
            get {
                return ResourceManager.GetString("GameBarcodeScannerPageMakeARequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string GameBarcodeScannerPageTitle {
            get {
                return ResourceManager.GetString("GameBarcodeScannerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find what you&apos;re looking for?.
        /// </summary>
        public static string GameLibraryListPageCantFindGame {
            get {
                return ResourceManager.GetString("GameLibraryListPageCantFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load games due to an unexpected error..
        /// </summary>
        public static string GameLibraryListPageEmptyGenericError {
            get {
                return ResourceManager.GetString("GameLibraryListPageEmptyGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load games due to an error on the server..
        /// </summary>
        public static string GameLibraryListPageEmptyServerError {
            get {
                return ResourceManager.GetString("GameLibraryListPageEmptyServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the entry above to search for games..
        /// </summary>
        public static string GameLibraryListPageInstructions {
            get {
                return ResourceManager.GetString("GameLibraryListPageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a request.
        /// </summary>
        public static string GameLibraryListPageMakeARequest {
            get {
                return ResourceManager.GetString("GameLibraryListPageMakeARequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string GameLibraryListPageTitle {
            get {
                return ResourceManager.GetString("GameLibraryListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Library.
        /// </summary>
        public static string GameLibraryTabbedPage {
            get {
                return ResourceManager.GetString("GameLibraryTabbedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GameOptionsPageDelete {
            get {
                return ResourceManager.GetString("GameOptionsPageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string GameOptionsPageStatus {
            get {
                return ResourceManager.GetString("GameOptionsPageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string GameOptionsPageUpdate {
            get {
                return ResourceManager.GetString("GameOptionsPageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to library.
        /// </summary>
        public static string GamePageAddToLibrary {
            get {
                return ResourceManager.GetString("GamePageAddToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently in:.
        /// </summary>
        public static string GamePageCurrentlyIn {
            get {
                return ResourceManager.GetString("GamePageCurrentlyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the selected game..
        /// </summary>
        public static string GamePageErrorMessage {
            get {
                return ResourceManager.GetString("GamePageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string GamePageOptions {
            get {
                return ResourceManager.GetString("GamePageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Games.
        /// </summary>
        public static string GamePageSimilarGames {
            get {
                return ResourceManager.GetString("GamePageSimilarGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notes cannot exceed 2048 characters..
        /// </summary>
        public static string GameRequestErrorMessageNotesMaxLength {
            get {
                return ResourceManager.GetString("GameRequestErrorMessageNotesMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot be empty or only contain whitespace..
        /// </summary>
        public static string GameRequestErrorMessageTitleEmpty {
            get {
                return ResourceManager.GetString("GameRequestErrorMessageTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot exceed 255 characters..
        /// </summary>
        public static string GameRequestErrorMessageTitleMaxLength {
            get {
                return ResourceManager.GetString("GameRequestErrorMessageTitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional notes.
        /// </summary>
        public static string GameRequestPageAdditionalNotes {
            get {
                return ResourceManager.GetString("GameRequestPageAdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your request. An admin will add the request game to the library as soon as possible. You will receive a notification when the request has been completed..
        /// </summary>
        public static string GameRequestPageRequestComplete {
            get {
                return ResourceManager.GetString("GameRequestPageRequestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string GameRequestPageSubmit {
            get {
                return ResourceManager.GetString("GameRequestPageSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GameRequestPageTitle {
            get {
                return ResourceManager.GetString("GameRequestPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GameUserEntriesTabbedPageTitle {
            get {
                return ResourceManager.GetString("GameUserEntriesTabbedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no games in .
        /// </summary>
        public static string GameUserEntryListPageEmpty {
            get {
                return ResourceManager.GetString("GameUserEntryListPageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load your games due to an unexpected error..
        /// </summary>
        public static string GameUserEntryListPageEmptyGenericError {
            get {
                return ResourceManager.GetString("GameUserEntryListPageEmptyGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load your games due to an error on the server..
        /// </summary>
        public static string GameUserEntryListPageEmptyServerError {
            get {
                return ResourceManager.GetString("GameUserEntryListPageEmptyServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep track of all your collections here in your library..
        /// </summary>
        public static string HomePageSubtitle {
            get {
                return ResourceManager.GetString("HomePageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password has been entered..
        /// </summary>
        public static string LoginErrorMessagePasswordEmpty {
            get {
                return ResourceManager.GetString("LoginErrorMessagePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username has been entered..
        /// </summary>
        public static string LoginErrorMessageUsernameEmpty {
            get {
                return ResourceManager.GetString("LoginErrorMessageUsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? .
        /// </summary>
        public static string LoginPageDontHaveAnAccount {
            get {
                return ResourceManager.GetString("LoginPageDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password?.
        /// </summary>
        public static string LoginPageForgottenPassword {
            get {
                return ResourceManager.GetString("LoginPageForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPageLogIn {
            get {
                return ResourceManager.GetString("LoginPageLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPagePassword {
            get {
                return ResourceManager.GetString("LoginPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string LoginPageSignUp {
            get {
                return ResourceManager.GetString("LoginPageSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginPageUsername {
            get {
                return ResourceManager.GetString("LoginPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 1 number.
        /// </summary>
        public static string PasswordRuleFour {
            get {
                return ResourceManager.GetString("PasswordRuleFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 8 characters.
        /// </summary>
        public static string PasswordRuleOne {
            get {
                return ResourceManager.GetString("PasswordRuleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password must contain:.
        /// </summary>
        public static string PasswordRulesHeader {
            get {
                return ResourceManager.GetString("PasswordRulesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 1 lower case letter.
        /// </summary>
        public static string PasswordRuleThree {
            get {
                return ResourceManager.GetString("PasswordRuleThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 1 upper case letter.
        /// </summary>
        public static string PasswordRuleTwo {
            get {
                return ResourceManager.GetString("PasswordRuleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password cannot be empty or only contain whitespace..
        /// </summary>
        public static string RecoveryErrorMessageConfirmPasswordEmpty {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageConfirmPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords must match..
        /// </summary>
        public static string RecoveryErrorMessageConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty or only contain whitespace..
        /// </summary>
        public static string RecoveryErrorMessagePasswordEmpty {
            get {
                return ResourceManager.GetString("RecoveryErrorMessagePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase character..
        /// </summary>
        public static string RecoveryErrorMessagePasswordLowercaseCharacter {
            get {
                return ResourceManager.GetString("RecoveryErrorMessagePasswordLowercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string RecoveryErrorMessagePasswordMinimumLength {
            get {
                return ResourceManager.GetString("RecoveryErrorMessagePasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        public static string RecoveryErrorMessagePasswordNumber {
            get {
                return ResourceManager.GetString("RecoveryErrorMessagePasswordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase character..
        /// </summary>
        public static string RecoveryErrorMessagePasswordUppercaseCharacter {
            get {
                return ResourceManager.GetString("RecoveryErrorMessagePasswordUppercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not contain any spaces..
        /// </summary>
        public static string RecoveryErrorMessagePasswordWhitespace {
            get {
                return ResourceManager.GetString("RecoveryErrorMessagePasswordWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery token should only contain alphanumeric characters..
        /// </summary>
        public static string RecoveryErrorMessageRecoveryTokenAlphanumeric {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageRecoveryTokenAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery token cannot be empty or only contain whitespace..
        /// </summary>
        public static string RecoveryErrorMessageRecoveryTokenEmpty {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageRecoveryTokenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery token must be exactly 30 characters long..
        /// </summary>
        public static string RecoveryErrorMessageRecoveryTokenLength {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageRecoveryTokenLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery token cannot contain any spaces..
        /// </summary>
        public static string RecoveryErrorMessageRecoveryTokenWhitespace {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageRecoveryTokenWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty or only contain whitespace..
        /// </summary>
        public static string RecoveryErrorMessageUsernameEmpty {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageUsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username can only contain letters, numbers, under-scores and hyphens..
        /// </summary>
        public static string RecoveryErrorMessageUsernameInvalidCharacters {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageUsernameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be between 1 and 255 characters..
        /// </summary>
        public static string RecoveryErrorMessageUsernameLength {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageUsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot contain any spaces..
        /// </summary>
        public static string RecoveryErrorMessageUsernameWhitespace {
            get {
                return ResourceManager.GetString("RecoveryErrorMessageUsernameWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RecoveryPageConfirmPassword {
            get {
                return ResourceManager.GetString("RecoveryPageConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to your email containing your recovery token. Please enter it in the input below along with your username and new password..
        /// </summary>
        public static string RecoveryPageInstructions {
            get {
                return ResourceManager.GetString("RecoveryPageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string RecoveryPageLogIn {
            get {
                return ResourceManager.GetString("RecoveryPageLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RecoveryPagePassword {
            get {
                return ResourceManager.GetString("RecoveryPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy &amp; Terms of Use.
        /// </summary>
        public static string RecoveryPagePrivacyPolicyAndTermsOfUse {
            get {
                return ResourceManager.GetString("RecoveryPagePrivacyPolicyAndTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string RecoveryPageRecover {
            get {
                return ResourceManager.GetString("RecoveryPageRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery token.
        /// </summary>
        public static string RecoveryPageRecoveryToken {
            get {
                return ResourceManager.GetString("RecoveryPageRecoveryToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered your password? .
        /// </summary>
        public static string RecoveryPageRememberedPassword {
            get {
                return ResourceManager.GetString("RecoveryPageRememberedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover account.
        /// </summary>
        public static string RecoveryPageTitle {
            get {
                return ResourceManager.GetString("RecoveryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string RecoveryPageUsername {
            get {
                return ResourceManager.GetString("RecoveryPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string RegisterPageAlreadyHaveAccount {
            get {
                return ResourceManager.GetString("RegisterPageAlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterPageConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterPageConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string RegisterPageEmailAddress {
            get {
                return ResourceManager.GetString("RegisterPageEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string RegisterPageLogIn {
            get {
                return ResourceManager.GetString("RegisterPageLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterPagePassword {
            get {
                return ResourceManager.GetString("RegisterPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy &amp; Terms of Use.
        /// </summary>
        public static string RegisterPagePrivacyPolicyAndTermsOfUse {
            get {
                return ResourceManager.GetString("RegisterPagePrivacyPolicyAndTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string RegisterPageSignUp {
            get {
                return ResourceManager.GetString("RegisterPageSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string RegisterPageUsername {
            get {
                return ResourceManager.GetString("RegisterPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password cannot be empty or only contain whitespace..
        /// </summary>
        public static string RegistrationErrorMessageConfirmPasswordEmpty {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageConfirmPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords must match..
        /// </summary>
        public static string RegistrationErrorMessageConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot be empty or only contain whitespace..
        /// </summary>
        public static string RegistrationErrorMessageEmailAddressEmpty {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageEmailAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string RegistrationErrorMessageEmailAddressInvalid {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty or only contain whitespace..
        /// </summary>
        public static string RegistrationErrorMessagePasswordEmpty {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase character..
        /// </summary>
        public static string RegistrationErrorMessagePasswordLowercaseCharacter {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordLowercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string RegistrationErrorMessagePasswordMinimumLength {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        public static string RegistrationErrorMessagePasswordNumber {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase character..
        /// </summary>
        public static string RegistrationErrorMessagePasswordUppercaseCharacter {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordUppercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not contain any spaces..
        /// </summary>
        public static string RegistrationErrorMessagePasswordWhitespace {
            get {
                return ResourceManager.GetString("RegistrationErrorMessagePasswordWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty or only contain whitespace..
        /// </summary>
        public static string RegistrationErrorMessageUsernameEmpty {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageUsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username can only contain letters, numbers, under-scores and hyphens..
        /// </summary>
        public static string RegistrationErrorMessageUsernameInvalidCharacters {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageUsernameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be between 1 and 255 characters..
        /// </summary>
        public static string RegistrationErrorMessageUsernameLength {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageUsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot contain any spaces..
        /// </summary>
        public static string RegistrationErrorMessageUsernameWhitespace {
            get {
                return ResourceManager.GetString("RegistrationErrorMessageUsernameWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have a token?.
        /// </summary>
        public static string RequestChangePasswordPageAlreadyHaveToken {
            get {
                return ResourceManager.GetString("RequestChangePasswordPageAlreadyHaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap below to receive your token to change your password..
        /// </summary>
        public static string RequestChangePasswordPageInstructions {
            get {
                return ResourceManager.GetString("RequestChangePasswordPageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string RequestChangePasswordPageSend {
            get {
                return ResourceManager.GetString("RequestChangePasswordPageSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here.
        /// </summary>
        public static string RequestChangePasswordPageTapHere {
            get {
                return ResourceManager.GetString("RequestChangePasswordPageTapHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request change password.
        /// </summary>
        public static string RequestChangePasswordPageTitle {
            get {
                return ResourceManager.GetString("RequestChangePasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string SettingsPageAccountSubtitle {
            get {
                return ResourceManager.GetString("SettingsPageAccountSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address.
        /// </summary>
        public static string SettingsPageChangeEmailAddress {
            get {
                return ResourceManager.GetString("SettingsPageChangeEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string SettingsPageChangePassword {
            get {
                return ResourceManager.GetString("SettingsPageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games, Books, Manga, Anime.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trak.
        /// </summary>
        public static string TrakTitle {
            get {
                return ResourceManager.GetString("TrakTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code cannot be empty or only contain whitespace..
        /// </summary>
        public static string VerificationErrorMessageVerificationCodeEmpty {
            get {
                return ResourceManager.GetString("VerificationErrorMessageVerificationCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code should only contain letters and numbers..
        /// </summary>
        public static string VerificationErrorMessageVerificationCodeInvalidCharacters {
            get {
                return ResourceManager.GetString("VerificationErrorMessageVerificationCodeInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of characters. The verification code will be between 1 and 5 characters..
        /// </summary>
        public static string VerificationErrorMessageVerificationCodeLength {
            get {
                return ResourceManager.GetString("VerificationErrorMessageVerificationCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code cannot contain any spaces..
        /// </summary>
        public static string VerificationErrorMessageVerificationCodeWhitespace {
            get {
                return ResourceManager.GetString("VerificationErrorMessageVerificationCodeWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have now sent you a confirmation email with your verification code..
        /// </summary>
        public static string VerificationPageConfirmation {
            get {
                return ResourceManager.GetString("VerificationPageConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven&apos;t received an email? .
        /// </summary>
        public static string VerificationPageHaventReceivedEmail {
            get {
                return ResourceManager.GetString("VerificationPageHaventReceivedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send again.
        /// </summary>
        public static string VerificationPageSendAgain {
            get {
                return ResourceManager.GetString("VerificationPageSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you..
        /// </summary>
        public static string VerificationPageTitle {
            get {
                return ResourceManager.GetString("VerificationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string VerificationPageVerificationCode {
            get {
                return ResourceManager.GetString("VerificationPageVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerificationPageVerify {
            get {
                return ResourceManager.GetString("VerificationPageVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
